;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Item.Special.Obtacle",NewTagName="Item.Special.Obstacle")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Skill.Kick",DevComment="")
+GameplayTagList=(Tag="Character.Skill.Kick.Hit",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.Attack.Knockback",DevComment="")
+GameplayTagList=(Tag="Item.Buff.KickPowerUp",DevComment="")
+GameplayTagList=(Tag="Item.Buff.SpeedUp",DevComment="")
+GameplayTagList=(Tag="Item.Debuff.SpeedDown",DevComment="")
+GameplayTagList=(Tag="Item.Special.Obstacle",DevComment="")
+GameplayTagList=(Tag="Team.Blue",DevComment="")
+GameplayTagList=(Tag="Team.Red",DevComment="")
+GameplayTagList=(Tag="Team.Waiting",DevComment="")

